import { useState } from "react";
import Tag from "../../components/ui/Tag";

const TAG_COLORS = {
    "Research Digest": "#4A8FD4",
    "Opinion": "#f59e0b",
    "Announcement": "#22c55e",
    "Technical": "#8b5cf6",
};

const INITIAL_DRAFTS = [
    {
        id: 1, status: "pending",
        tag: "Research Digest",
        title: "Gemini 2.0 Flash vs GPT-4o Mini: Benchmark Analysis for Low-Resource NLP",
        generatedAt: "2 hours ago",
        sources: ["arxiv.org/abs/2501.12345", "huggingface.co/blog/gemini-flash", "paperswithcode.com/sota/nlp"],
        excerpt: "We compared Gemini 2.0 Flash and GPT-4o Mini across 8 NLP benchmarks with a focus on African language performance...",
        content: "## Overview\n\nThis week's research digest covers the head-to-head comparison between Google's Gemini 2.0 Flash and OpenAI's GPT-4o Mini...\n\n## Key Findings\n\nOn standard English benchmarks, both models perform comparably. The divergence appears in low-resource language tasks...\n\n## DFT Labs Take\n\nFor our LearnForge product which requires strong Yoruba and Hausa performance, Gemini 2.0 Flash shows a 12% edge...",
    },
    {
        id: 2, status: "pending",
        tag: "Research Digest",
        title: "New WHO Guidelines on AI-Assisted Diagnostics: What It Means for Health AI Builders",
        generatedAt: "2 hours ago",
        sources: ["who.int/publications/ai-diagnostics-2026", "thelancet.com/ai-health-guidelines", "nejm.org/ai-clinical-tools"],
        excerpt: "The World Health Organization released updated guidelines for AI-assisted diagnostic tools. We break down the implications for developers building in this space...",
        content: "## The New Guidelines\n\nWHO's updated framework introduces three new requirements for clinical AI tools deployed in low-and-middle-income countries...\n\n## What Changes for Developers\n\nExplainability is now a hard requirement, not a nice-to-have. Every diagnostic decision must include a human-readable confidence breakdown...\n\n## DFT Labs Take\n\nMedScan AI v2.0's explainability dashboard was built with exactly this kind of regulatory direction in mind. We're ahead of the curve here.",
    },
    {
        id: 3, status: "pending",
        tag: "Technical",
        title: "LangGraph vs CrewAI for Multi-Agent Pipelines: A Practical Comparison",
        generatedAt: "2 hours ago",
        sources: ["langchain-ai.github.io/langgraph", "github.com/joaomdmoura/crewai", "arxiv.org/abs/2501.98765"],
        excerpt: "Both LangGraph and CrewAI have emerged as leading frameworks for multi-agent AI systems. We tested both for our research digest pipeline and share the tradeoffs...",
        content: "## Background\n\nWhen building our research digest agent, we evaluated both frameworks extensively...\n\n## LangGraph Strengths\n\nStrict graph-based execution makes debugging deterministic. State management is explicit and auditable...\n\n## CrewAI Strengths\n\nFaster to prototype. Role-based agent design maps naturally to real-world team workflows...\n\n## DFT Labs Take\n\nWe chose LangGraph for production because the determinism and explicit state management reduce surprises in scheduled pipelines.",
    },
];

export default function AdminBlog() {
    const [drafts, setDrafts] = useState(INITIAL_DRAFTS);
    const [editing, setEditing] = useState(null); // draft id being edited
    const [editContent, setEditContent] = useState({});

    const startEdit = (draft) => {
        setEditing(draft.id);
        setEditContent({ title: draft.title, content: draft.content, tag: draft.tag });
    };

    const saveEdit = (id) => {
        setDrafts(ds => ds.map(d => d.id === id ? { ...d, ...editContent } : d));
        setEditing(null);
    };

    const publish = (id) => {
        setDrafts(ds => ds.map(d => d.id === id ? { ...d, status: "published" } : d));
    };

    const discard = (id) => {
        setDrafts(ds => ds.filter(d => d.id !== id));
    };

    const inputStyle = {
        width: "100%", background: "rgba(255,255,255,0.04)",
        border: "1px solid var(--border)", borderRadius: 10,
        padding: "10px 14px", color: "var(--text)", fontSize: 14,
        outline: "none", fontFamily: "inherit",
    };

    return (
        <div>
            <div style={{ marginBottom: 32 }}>
                <h1 style={{ fontSize: 26, fontWeight: 800, color: "var(--text)", fontFamily: "var(--font-display)", marginBottom: 6 }}>
                    Blog Drafts
                </h1>
                <p style={{ fontSize: 14, color: "var(--text-faint)" }}>
                    {drafts.filter(d => d.status === "pending").length} drafts waiting for your review — generated by the Research Agent.
                </p>
            </div>

            <div style={{ display: "flex", flexDirection: "column", gap: 24 }}>
                {drafts.map(draft => (
                    <div key={draft.id} style={{
                        background: "var(--bg-card)", border: `1px solid ${draft.status === "published" ? "rgba(34,197,94,0.3)" : "var(--border)"}`,
                        borderRadius: 16, overflow: "hidden",
                    }}>
                        {/* Draft header */}
                        <div style={{ padding: "20px 24px", borderBottom: "1px solid var(--border)" }}>
                            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 16, flexWrap: "wrap" }}>
                                <div style={{ flex: 1 }}>
                                    <div style={{ display: "flex", gap: 10, alignItems: "center", marginBottom: 10, flexWrap: "wrap" }}>
                                        <Tag label={draft.tag} color={TAG_COLORS[draft.tag] || "var(--blue)"} />
                                        <Tag label={draft.status === "published" ? "Published ✓" : "Pending Review"} color={draft.status === "published" ? "#22c55e" : "#f59e0b"} />
                                        <span style={{ fontSize: 12, color: "var(--text-faint)" }}>Generated {draft.generatedAt}</span>
                                    </div>
                                    {editing === draft.id ? (
                                        <input value={editContent.title} onChange={e => setEditContent(c => ({ ...c, title: e.target.value }))} style={{ ...inputStyle, fontSize: 17, fontWeight: 700, marginBottom: 8 }} />
                                    ) : (
                                        <h3 style={{ fontSize: 17, fontWeight: 700, color: "var(--text)", fontFamily: "var(--font-display)", lineHeight: 1.4 }}>{draft.title}</h3>
                                    )}
                                </div>
                                {draft.status !== "published" && (
                                    <div style={{ display: "flex", gap: 8, flexShrink: 0 }}>
                                        {editing === draft.id ? (
                                            <>
                                                <button onClick={() => saveEdit(draft.id)} style={{ background: "var(--blue-dim)", border: "1px solid var(--border-blue)", color: "var(--blue)", borderRadius: 8, padding: "8px 16px", fontSize: 12, fontWeight: 600, cursor: "pointer", fontFamily: "inherit" }}>Save</button>
                                                <button onClick={() => setEditing(null)} style={{ background: "none", border: "1px solid var(--border)", color: "var(--text-muted)", borderRadius: 8, padding: "8px 16px", fontSize: 12, fontWeight: 600, cursor: "pointer", fontFamily: "inherit" }}>Cancel</button>
                                            </>
                                        ) : (
                                            <>
                                                <button onClick={() => startEdit(draft)} style={{ background: "var(--blue-dim)", border: "1px solid var(--border-blue)", color: "var(--blue)", borderRadius: 8, padding: "8px 16px", fontSize: 12, fontWeight: 600, cursor: "pointer", fontFamily: "inherit" }}>✏️ Edit</button>
                                                <button onClick={() => publish(draft.id)} style={{ background: "rgba(34,197,94,0.12)", border: "1px solid rgba(34,197,94,0.3)", color: "#22c55e", borderRadius: 8, padding: "8px 16px", fontSize: 12, fontWeight: 600, cursor: "pointer", fontFamily: "inherit" }}>🚀 Publish</button>
                                                <button onClick={() => discard(draft.id)} style={{ background: "rgba(239,68,68,0.08)", border: "1px solid rgba(239,68,68,0.2)", color: "#ef4444", borderRadius: 8, padding: "8px 16px", fontSize: 12, fontWeight: 600, cursor: "pointer", fontFamily: "inherit" }}>🗑 Discard</button>
                                            </>
                                        )}
                                    </div>
                                )}
                            </div>
                        </div>

                        {/* Content preview / editor */}
                        <div style={{ padding: "20px 24px" }}>
                            {editing === draft.id ? (
                                <textarea
                                    value={editContent.content}
                                    onChange={e => setEditContent(c => ({ ...c, content: e.target.value }))}
                                    rows={12}
                                    style={{ ...inputStyle, resize: "vertical", lineHeight: 1.7 }}
                                />
                            ) : (
                                <p style={{ fontSize: 14, color: "var(--text-muted)", lineHeight: 1.8 }}>
                                    {draft.excerpt}
                                </p>
                            )}

                            {/* Sources */}
                            <div style={{ marginTop: 16, paddingTop: 16, borderTop: "1px solid var(--border)" }}>
                                <div style={{ fontSize: 11, color: "var(--text-faint)", letterSpacing: "0.08em", marginBottom: 10 }}>AGENT SOURCES</div>
                                <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
                                    {draft.sources.map(src => (
                                        <a key={src} href={`https://${src}`} target="_blank" rel="noreferrer" style={{
                                            fontSize: 11, color: "var(--blue)", background: "var(--blue-dim)",
                                            border: "1px solid var(--border-blue)", borderRadius: 6,
                                            padding: "4px 10px", textDecoration: "none",
                                        }}>
                                            🔗 {src}
                                        </a>
                                    ))}
                                </div>
                            </div>
                        </div>
                    </div>
                ))}
            </div>
        </div>
    );
}